# Generated by Django 5.1.4 on 2025-05-07 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_domain_remove_page_theme_remove_section_page'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
