# Generated by Django 5.1.4 on 2025-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
