# Generated by Django 5.1.4 on 2025-05-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userpayment_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
