# Generated by Django 5.1.4 on 2025-05-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='theme',
        ),
    ]
