# Generated by Django 5.1.4 on 2025-05-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_theme'),
        ('themes', '0002_pagetemplate_delete_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.pagetemplate'),
        ),
    ]
