# Generated by Django 5.1.4 on 2025-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='page',
            name='og_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
