# Generated by Django 5.1.4 on 2025-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_meta_description_page_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('features', 'Features'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('faq', 'FAQ')], default='hero', max_length=20),
            preserve_default=False,
        ),
    ]
