# Generated by Django 5.1.4 on 2025-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome or Feather icon class', max_length=100),
        ),
    ]
