# Generated by Django 5.1.4 on 2025-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('benefits', 'Benefits/Value Proposition'), ('testimonials', 'Testimonials'), ('pricing', 'Pricing'), ('faq', 'FAQ'), ('final_cta', 'Final CTA')], max_length=20),
        ),
    ]
