# Generated by Django 5.1.4 on 2025-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='pricing_benefits',
            field=models.TextField(blank=True, help_text='List of benefits (separated by line breaks)'),
        ),
        migrations.AddField(
            model_name='page',
            name='pricing_bonuses',
            field=models.TextField(blank=True, help_text='Bonus items (line break separated)'),
        ),
    ]
